### ISSUE TITLE
In session modify PSModule path to point to relative dir with custom resources

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#247]
To enable to use custom modules or those that differ from those in repository - also necessary for composite DSC resources

**Comment by MS-MatthewWalker** [comment]
https://msdn.microsoft.com/en-us/library/dd878326%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 for info about transient nature of modifying PSModulePath

**Comment by PlagueHO** [comment]
I've finished this change but I can't merge it to Dev/Master yet because I don't have access to one of the repos till tomorrow (I've got this project being automatically stored in multiple locations so that I can run integration tests on it).

But you can find the changes in this branch:
https://github.com/PlagueHO/LabBuilder/tree/Enhancement-247/Custom-Module-Path-Support

I'll merge it tomorrow.
