### ISSUE TITLE
New-VMSwitch : Cannot find a physical network adapter named....

### ISSUE THREAD

**Issue by MrUtOpiK** [PlagueHO/LabBuilder#265]
Information : 
- [ 5] Version of PowerShell you're using
- [ Console Host] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [ WS2012R2] Operating system you're running
- [ Latest] Version of LabBuilder you're using (use `Get-Module -Name LabBuilder`)

When I try to build a Lab, I have this error message : 

New-VMSwitch : Cannot find a physical network adapter named Intel(R) PRO/1000 PT Dual Port Server Adapter #2.
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\0.8.3.995\lib\public\switch.ps1:286 char:29

On my lab the nic teaming is enabled. (Intel(R) PRO/1000 PT Dual Port Server Adapter #2 + Intel(R) PRO/1000 PT Dual Port Server Adapter #1)

If someone can help me... :) Many thanks guys !

**Comment by MrUtOpiK** [comment]
This is because, in the script "switch.ps1" the command "Get-NetAdapter -Physical" is used.

How can I do if I want to use my nic teaming card ?

Many thanks

**Comment by PlagueHO** [comment]
Hi @MrUtOpiK , Good question. I'll have a look at this over the weekend. I've been neglecting this project a bit lately,  so I'll look at adding a new feature to support this.

**Comment by MrUtOpiK** [comment]
Perfect. This project is awesome :)
Many thanks for your help !

**Comment by PlagueHO** [comment]
@MrUtOpiK - really glad you find it useful! Always nice to hear!

Anyway, I've made a change that I think should allow your NIC Teams to be able to bound to an External VM Switch. I've merged the changes to the Dev branch. I'll merge them to the Master branch in a few days so that they're published to PSGallery - I've just got a few more changes to make before next release to PSGallery.
