### ISSUE TITLE
How to install a exe

### ISSUE THREAD

**Issue by andlo** [PlagueHO/LabBuilder#281]
Hi - I am testing Labuilder and it looks great  I have also looked at Lability which is altså a lab building module, and AutomatedLab to. Both has different approch for making a lab. 
But ofcause ive got some questions....
 
How to install a package containing an EXE file? Specifik I need to install Exchange, which requeres UcmaRuntimeSetup.exe to be installed.

**Comment by PlagueHO** [comment]
Hi @andlo - really glad you like the look of this! The Lability project is a fantastic project - I try and help out with that project too when I can (I contribute to the DSC resources to help :grin:).

That is a good question. I've provided support to allow MSU files to be installed into an image (prior to first boot), but didn't allow for injecting additional files (such as EXE's) into the VM HD.

This would be fairly easy to do. What I could do is:
1. Add a new type of <resource> in the Lab Config XML file that is just the path to a file that can be injected into an image.
e.g.
```
 <resources>
    <file name="UcmaRuntimeSetup.exe"
         url="https://download.microsoft.com/download/2/C/4/2C47A5C1-A1F3-4843-B9FE-84C0032C61EC/UcmaRuntimeSetup.exe" />
</resources>
```
2. Add a new VM or VM Template parameter that can contain a list of any resource files (from the <resources> list) and will inject it into the VM HD image when it is created:
E.g.
```
<vm name="EXCHANGE01"
  template="Template Windows Server 2016 Datacenter CORE"
  computername="EXCHANGE01"
  supportfile="UcmaRuntimeSetup.exe">
```
This would ensure that this file is placed into c:\Windows\Setup\  in the VM so that it could then be used by a DSC Config file (installed using the DSC xPackage resource I'd expect).

Does that sound like it might work for your scenario?
