### ISSUE TITLE
Packages aren't being applied to Nano Images

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#49]
Parsing of packages isn't properly injecting the packages into the Nano image, also need to extend functionality in actual VM creation to add additional packages if Nano image

**Comment by PlagueHO** [comment]
Ok. Leave this with me. I'm reworking this code at the moment and adding unit tests so I'll resolve this ASAP. I'm also moving the Nano build code over to use the Nano Module that comes with TP4 so that we stick with the official process as well as automatically supporting any new Nano Packages that get added.

**Comment by PlagueHO** [comment]
Packages are now being applied, but I still need to allow packages to also be applied at the VM creation stage as well.
